graph LR
    classDef green fill:#90EE90,stroke:#333,stroke-width:2px;
    classDef lightPurple fill:#E6E6FA,stroke:#333,stroke-width:2px;
    classDef mathlib fill:#90EE90,stroke:#333,stroke-width:2px;
    %%{init: {'flowchart': {'nodeSpacing': 30, 'rankSpacing': 30, 'curve': 'basis', 'wrappingWidth': 100}}}%%
    Canonical --> GeneratedSubmodel
    Tautology --> Proof
    FormSubstitution --> Proof
    IteratedModalities --> Proof
    Mathlib --> Util
    TypeIff --> Util
    Form --> IteratedModalities
    Soundness --> Completeness
    ProofUtils --> Completeness
    Eval --> Tautology
    Nominals --> Substitutions
    Variants --> Satisfaction
    Satisfaction --> Truth
    RenameBound --> ProofUtils
    Form --> Eval
    Util --> Eval
    GeneralModel --> Canonical
    Soundness --> RenameBound
    ListUtils --> RenameBound
    NominalSubstitution --> FormSubstitution
    PROP --> Form
    SVAR --> Form
    NOM --> Form
    Form --> FormCountable
    Util --> FormCountable
    Proof --> LanguageExtension
    Substitutions --> LanguageExtension
    Util --> LanguageExtension
    Model --> Tautologies
    Tautology --> Tautologies
    FormSubstitution --> Variables
    Lemmas --> Soundness
    Tautologies --> Soundness
    Proof --> Soundness
    RenameBound --> GeneralModel
    Form --> New_NOM
    Util --> New_NOM
    Tautology --> ListUtils
    FormCountable --> Lindenbaum
    RenameBound --> Lindenbaum
    FormSubstitution --> Lindenbaum
    CompletedModel --> StandardCompletedModel
    TotalSet --> NOM
    GeneratedSubmodel --> WitnessedModel
    ProofUtils --> MCS
    Truth --> Lemmas
    New_NOM --> NominalSubstitution
    Lindenbaum --> ExistenceLemma
    ProofUtils --> ExistenceLemma
    Variables --> Nominals
    IteratedModalities --> Nominals
    Model --> Variants
    Substitutions --> Model
    Mathlib --> TotalSet
    WitnessedModel --> CompletedModel
    MCS --> CompletedModel
    class GeneratedSubmodel,Proof,Util,IteratedModalities,Truth,TypeIff,Eval,FormSubstitution,PROP,Form,Variables,GeneralModel,New_NOM,SVAR,ListUtils,NOM,WitnessedModel,Model,TotalSet green;
    class Completeness,Tautology,Substitutions,Satisfaction,ProofUtils,Canonical,RenameBound,FormCountable,LanguageExtension,Tautologies,Soundness,Lindenbaum,StandardCompletedModel,MCS,Lemmas,NominalSubstitution,ExistenceLemma,Nominals,Variants,CompletedModel lightPurple;
    class Mathlib mathlib;
